version: "3.3"

services:
    caldera:
        build:
            context: ./docker
        ports:
            - "8888:8888"
        volumes:
            - "./docker-mongo-data:/data/db"
            - "~/code/caldera/caldera/app/operation:/root/caldera/caldera/app/operation"
